import tempfile
import unittest
from pathlib import Path
from unittest.mock import Mock, patch

from velum.network.dns import ResolvedDNS


class DNSTests(unittest.TestCase):
    def test_foreign_resolver_refused(self):
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / 'resolv.conf'
            path.write_text('nameserver 192.0.2.1\n')
            dns = ResolvedDNS(Mock(), Mock(), path)
            with self.assertRaisesRegex(RuntimeError, 'Unsupported DNS configuration'):
                dns.preflight()
            self.assertEqual(path.read_text(), 'nameserver 192.0.2.1\n')

    def test_link_only_changes(self):
        runner, tx = Mock(), Mock()
        ResolvedDNS(runner, tx).configure()
        self.assertIn('vpn0', tx.apply.call_args.args[0])
        self.assertEqual(tx.apply.call_args.args[1], ['/usr/bin/resolvectl', 'revert', 'vpn0'])

    @patch('velum.network.dns.socket.create_connection')
    def test_networkmanager_regular_stub_file_supported(self, connect):
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / 'resolv.conf'
            original = '# Generated by NetworkManager\n  nameserver\t127.0.0.53 # stub\noptions edns0 trust-ad\n'
            path.write_text(original)
            runner = Mock()
            ResolvedDNS(runner, Mock(), path).preflight()
            runner.run.assert_called_once_with('/usr/bin/resolvectl', 'status')
            connect.assert_called_once_with(('127.0.0.53', 53), timeout=2)
            self.assertFalse(path.is_symlink())
            self.assertEqual(path.read_text(), original)

    @patch('velum.network.dns.socket.create_connection')
    def test_stub_symlink_supported(self, connect):
        with tempfile.TemporaryDirectory() as d:
            target = Path(d) / 'stub-resolv.conf'
            target.write_text('nameserver 127.0.0.53\n')
            path = Path(d) / 'resolv.conf'
            path.symlink_to(target)
            ResolvedDNS(Mock(), Mock(), path).preflight()
            self.assertTrue(path.is_symlink())

    def test_mixed_or_missing_resolvers_rejected(self):
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / 'resolv.conf'
            for content in ('nameserver 127.0.0.53\nnameserver 1.1.1.1\n',
                            'nameserver\n', '# empty\n'):
                path.write_text(content)
                runner = Mock()
                with self.assertRaises(RuntimeError):
                    ResolvedDNS(runner, Mock(), path).preflight()
                runner.run.assert_not_called()

    @patch('velum.network.dns.socket.create_connection', side_effect=OSError('refused'))
    def test_inactive_stub_rejected(self, connect):
        with tempfile.TemporaryDirectory() as d:
            path = Path(d) / 'resolv.conf'
            path.write_text('nameserver 127.0.0.53\n')
            with self.assertRaisesRegex(RuntimeError, 'not reachable'):
                ResolvedDNS(Mock(), Mock(), path).preflight()
